### ISSUE TITLE
Couldn't find "libopencv_java3.so"

### ISSUE THREAD

**Issue by SachinGanesh** [LeeJeongHwi/Mediapipe_pose_Tracking_AAR_example#1]
I can build the application. When running, the app crashes with error **couldn't find "libopencv_java3.so"**. What could be the issue?

```
FATAL EXCEPTION: main
    Process: com.example.posetest, PID: 3799
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.posetest-mXAw8DBQVYrkzGKI_Loc7A==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.posetest-mXAw8DBQVYrkzGKI_Loc7A==/lib/arm, /data/app/com.example.posetest-mXAw8DBQVYrkzGKI_Loc7A==/base.apk!/lib/armeabi-v7a, /system/lib, /product/lib]]] couldn't find "libopencv_java3.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at com.example.myapplication.MainActivity.<clinit>(MainActivity.java:88)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1250)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3252)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3489)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2073)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:225)
        at android.app.ActivityThread.main(ActivityThread.java:7563)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)
```

**Comment by LeeJeongHwi** [comment]
Hi @SachinGanesh ! 

This is not the right reason, but I think you should download the armeabi-v7a version of libopencv.

there is arm64-v8a version of libopencv in my repository 

so, create the folder(armeabi-v7a) in `/app/src/main/jniLibs` and put what you downloaded in it.

if the same error occurs, please open the issue on Mediapipe Official Github.

Thank you!

**Comment by SachinGanesh** [comment]
HI @LeeJeongHwi Thank you. Yes its indeed the missing file for the given architecture.
